/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface HeritageRegistryInterface extends Interface {
    getFunction(nameOrSignature: "getVersion" | "publishVersion"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "HeritageVersionPublished"): EventFragment;

    encodeFunctionData(functionFragment: 'getVersion', values: [BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'publishVersion', values: [BytesLike, BigNumberish, BytesLike]): string;

    decodeFunctionResult(functionFragment: 'getVersion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'publishVersion', data: BytesLike): Result;
  }

  
    export namespace HeritageVersionPublishedEvent {
      export type InputTuple = [heritageId: BytesLike, version: BigNumberish, dataHash: BytesLike, timestamp: BigNumberish];
      export type OutputTuple = [heritageId: string, version: bigint, dataHash: string, timestamp: bigint];
      export interface OutputObject {heritageId: string, version: bigint, dataHash: string, timestamp: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface HeritageRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): HeritageRegistry;
    waitForDeployment(): Promise<this>;

    interface: HeritageRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    getVersion: TypedContractMethod<
      [heritageId: BytesLike, version: BigNumberish, ],
      [[string, bigint] & {dataHash: string, timestamp: bigint }],
      'view'
    >
    

    
    publishVersion: TypedContractMethod<
      [heritageId: BytesLike, version: BigNumberish, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'getVersion'): TypedContractMethod<
      [heritageId: BytesLike, version: BigNumberish, ],
      [[string, bigint] & {dataHash: string, timestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'publishVersion'): TypedContractMethod<
      [heritageId: BytesLike, version: BigNumberish, dataHash: BytesLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'HeritageVersionPublished'): TypedContractEvent<HeritageVersionPublishedEvent.InputTuple, HeritageVersionPublishedEvent.OutputTuple, HeritageVersionPublishedEvent.OutputObject>;

    filters: {
      
      'HeritageVersionPublished(bytes32,uint256,bytes32,uint256)': TypedContractEvent<HeritageVersionPublishedEvent.InputTuple, HeritageVersionPublishedEvent.OutputTuple, HeritageVersionPublishedEvent.OutputObject>;
      HeritageVersionPublished: TypedContractEvent<HeritageVersionPublishedEvent.InputTuple, HeritageVersionPublishedEvent.OutputTuple, HeritageVersionPublishedEvent.OutputObject>;
    
    };
  }