/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { HeritageRegistry } from './HeritageRegistry.js';
export * as factories from './factories/index.js';
export { HeritageRegistry__factory } from './factories/HeritageRegistry__factory.js';