/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../common.js"
  import type { HeritageRegistry, HeritageRegistryInterface } from "../HeritageRegistry.js";

  const _abi = [
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": true,
        "internalType": "bytes32",
        "name": "heritageId",
        "type": "bytes32"
      },
      {
        "indexed": true,
        "internalType": "uint256",
        "name": "version",
        "type": "uint256"
      },
      {
        "indexed": false,
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      },
      {
        "indexed": false,
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "name": "HeritageVersionPublished",
    "type": "event"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "heritageId",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "version",
        "type": "uint256"
      }
    ],
    "name": "getVersion",
    "outputs": [
      {
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "timestamp",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "heritageId",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "version",
        "type": "uint256"
      },
      {
        "internalType": "bytes32",
        "name": "dataHash",
        "type": "bytes32"
      }
    ],
    "name": "publishVersion",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506102508061001c5f395ff3fe608060405234801561000f575f5ffd5b5060043610610034575f3560e01c8063af904a0614610038578063f2f2eed714610064575b5f5ffd5b61004b6100463660046101d1565b610079565b6040805192835260208301919091520160405180910390f35b6100776100723660046101f1565b6100db565b005b5f5f5f8484604051602001610098929190918252602082015260400190565b60408051808303601f1901815282825280516020918201205f90815280825282902083830190925281548084526001909201549201829052969095509350505050565b604080516020808201869052818301859052825180830384018152606090920183528151918101919091205f8181529182905291902060010154156101665760405162461bcd60e51b815260206004820152601960248201527f56657273696f6e20616c7265616479207075626c697368656400000000000000604482015260640160405180910390fd5b6040805180820182528381524260208083018281525f8681528083528590209351845551600190930192909255825185815291820152849186917f574ac940497ce5276b4ef444d3f3842e79a9e4b57c75bb16a593b82805126130910160405180910390a350505050565b5f5f604083850312156101e2575f5ffd5b50508035926020909101359150565b5f5f5f60608486031215610203575f5ffd5b50508135936020830135935060409092013591905056fea26469706673582212205b19ecc69d56d359a15b0dc78ca978d553728e7fee4850be97cedbf939e8a56464736f6c634300081c0033";

  
      type HeritageRegistryConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: HeritageRegistryConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class HeritageRegistry__factory extends ContractFactory {
    
      constructor(...args: HeritageRegistryConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(overrides || {});
    };
    override deploy(overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(overrides || {}) as Promise<HeritageRegistry & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): HeritageRegistry__factory {
      return super.connect(runner) as HeritageRegistry__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): HeritageRegistryInterface {
      return new Interface(_abi) as HeritageRegistryInterface;
    }
    
    override attach(address: string | Addressable): HeritageRegistry {
      return super.attach(address) as HeritageRegistry;
    }
  static connect(address: string, runner?: ContractRunner | null): HeritageRegistry {
      return new Contract(address, _abi, runner) as unknown as HeritageRegistry;
    }
  }

  
  